// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDds7-sWQ1T3ZT59zU3RHDfU4B0tlvlt0Q',
    appId: '1:175352529180:web:f939c7488ce5a367f47ad9',
    messagingSenderId: '175352529180',
    projectId: 'iaparaaprender-9623a',
    authDomain: 'iaparaaprender-9623a.firebaseapp.com',
    storageBucket: 'iaparaaprender-9623a.firebasestorage.app',
    measurementId: 'G-21VN5XK8RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNWyYz_1Q9FU3Iw-lu_7LVlLYgHM6NE0',
    appId: '1:175352529180:android:d5cbd7c29dec3021f47ad9',
    messagingSenderId: '175352529180',
    projectId: 'iaparaaprender-9623a',
    storageBucket: 'iaparaaprender-9623a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1hatSEhzlW1IySo0Xk2nMcwF8Gn-kOI',
    appId: '1:175352529180:ios:f39ddb0c15386274f47ad9',
    messagingSenderId: '175352529180',
    projectId: 'iaparaaprender-9623a',
    storageBucket: 'iaparaaprender-9623a.firebasestorage.app',
    iosBundleId: 'com.example.grokstreet',
  );
}
